using DataVisualiser.UI.Charts.Interfaces;
using DataVisualiser.UI.Charts.Adapters;
namespace DataVisualiser.UI.Charts.Infrastructure;

public sealed record ChartControllerFactoryResult(MainChartControllerAdapter Main, NormalizedChartControllerAdapter Normalized, DiffRatioChartControllerAdapter DiffRatio, DistributionChartControllerAdapter Distribution, WeekdayTrendChartControllerAdapter WeekdayTrend, TransformDataPanelControllerAdapter Transform, BarPieChartControllerAdapter BarPie, IChartControllerRegistry Registry);
